### ISSUE TITLE
Cannot load configuration class: com.okta.spring.boot.oauth.OktaOAuth2AutoConfig

### ISSUE THREAD

**Issue by d8tamgitadmin** [okta/okta-spring-boot#147]
Can not start Spring Boot Application with the following error:

java.lang.IllegalStateException: Cannot load configuration class: com.okta.spring.boot.oauth.OktaOAuth2AutoConfig

`Caused by: java.lang.ClassNotFoundException: org.springframework.security.oauth2.client.oidc.web.logout.OidcClientInitiatedLogoutSuccessHandler
`

```
application.yaml:spring:
  profiles: dev
okta:
  oauth2:
    issuer: https://{}okta.com/oauth2/default
    client-id: foo
    client-secret: bar
```

pom.xml for oauth and security:
```
<dependency>
			<groupId>com.okta.spring</groupId>
			<artifactId>okta-spring-boot-starter</artifactId>
			<version>1.3.0</version>
		</dependency>
```

Java version is 1.8.
