### ISSUE TITLE
Token validation fails when using org authorization server with a custom domain

### ISSUE THREAD

**Issue by App13Pie** [okta/okta-spring-boot#316]
:information_source: **If you have a question**, please post it on the [Okta Developer Forum](https://devforum.okta.com) instead. Issues in this repository are reserved for bug reports and feature requests only.

### I'm submitting a
  - [x] bug report
  - [ ] feature request

### Background info

I am using the org authorization server to log users in.
I created a custom domain for my okta org and now I can't log in anymore.

### Expected behavior

I should be able to login as if I was not using a custom domain.

### What went wrong?

Token validation fails.

I get this error message in console:
DEBUG [reactor-http-nio-5] o.s.s.w.s.a.AuthenticationWebFilter: Authentication failed: An error occurred while attempting to authenticate: 
DEBUG [reactor-http-nio-5] o.s.s.w.s.DefaultServerRedirectStrategy: Redirecting to '/login?error'

And the login page shows this error: "Invalid credentials"

### Steps to reproduce

Use the org authorization server with a custom domain.

**Comment by VitaliiTytarenko-okta** [comment]
Hello @App13Pie,
Thank you for your report.
Provide more details, please, to better understand your issue.
- does it work when you switch to an Okta domain?
- what example are you using?
- share your _HttpSecurity_ config and `application.yml`

**Comment by App13Pie** [comment]
It works fine when I use the https://dev-xxxxxxx.okta.com domain.

I'm just creating a demo app with one endpoint.

Security config is:
```
@Bean
public SecurityWebFilterChain securityFilterChain(ServerHttpSecurity http) {
    http.csrf().disable()
            .authorizeExchange().anyExchange().authenticated()
            .and().oauth2Login();

    return http.build();
}
```

And application.yml is:
```
okta:
  oauth2:
    issuer: https://dev-auth.example.com
    audience: https://dev-auth.example.com
    client-id: xxxxx
    client-secret: xxxxx
    scopes:
      - openid
      - profile
      - email
      - okta.groups.read
      - okta.groups.manage
      - okta.users.read
      - okta.users.manage

```

**Comment by VitaliiTytarenko-okta** [comment]
Internal ref [OKTA-409487](https://oktainc.atlassian.net/browse/OKTA-409487)

**Comment by bdemers** [comment]
@App13Pie which version of the Okta Spring Boot Starter are you using?

**Comment by App13Pie** [comment]
I use Okta Spring Boot Start 2.1.0
And I use Spring Boot 2.5.2

**Comment by sergiishamrai-okta** [comment]
@App13Pie Thanks for your question!

Okta help center has [this](https://support.okta.com/help/s/article/Signature-Validation-Failed-on-Access-Token?language=en_US) article with a resolution for the issue.

Feel free to contact the Okta help center.

**Comment by App13Pie** [comment]
I have setup the opaque token properties in application.yml:
```
spring:
  security:
    oauth2:
      resourceserver:
        opaque-token:
          introspection-uri: ${okta.oauth2.issuer}/v1/introspect
          client-id: xxxxx
          client-secret: xxxxx
```
When using dev-xxxxxxx.okta.com, everything works as intended, token validation is done by introspection.
But when using dev-auth.example.com, token validation is done with org authorization server keys so it fails
It seems like opaque token validation is not properly configured for my custom domain.
